package com.sirier.domain;
// Generated 2017-8-19 23:11:45 by Hibernate Tools 3.2.2.GA


import org.hibernate.annotations.GenericGenerator;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "auth_function"
        , catalog = "bos2"
        , uniqueConstraints = @UniqueConstraint(columnNames = "NAME")
)
public class Function implements java.io.Serializable {


    private String id;
    private String name;
    private String code;
    private String description;
    private Set<Role> roles = new HashSet<Role>(0);

    public Function() {
    }

    public Function(String id) {
        this.id = id;
    }

    public Function(String name, String code, String description, Set<Role> roles) {
        this.name = name;
        this.code = code;
        this.description = description;
        this.roles = roles;
    }

    @GenericGenerator(name = "generator", strategy = "uuid")
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "ID", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "NAME", unique = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "CODE")
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "role_function", catalog = "bos2", joinColumns = {
            @JoinColumn(name = "FUNCTION_ID", nullable = false, updatable = false) },
            inverseJoinColumns = {
                    @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }


}


