package com.sirier.domain;
// Generated 2017-8-19 23:11:45 by Hibernate Tools 3.2.2.GA


import com.alibaba.fastjson.annotation.JSONField;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "auth_menu"
        , catalog = "bos2"
        , uniqueConstraints = @UniqueConstraint(columnNames = "NAME")
)
public class Menu implements java.io.Serializable {


    private String id;
    private Menu parentMenu;
    private String name;
    private String description;
    private String page;
    private String generatemenu;
    private Integer zindex;
    private Set<Menu> children = new HashSet<Menu>(0);
    private Set<Role> roles = new HashSet<Role>(0);


    //为combotree提供一个字段
    @Transient
    public String getText() {
        return this.name;
    }

    //动态生成菜单,父模块为null时返回0
    @Transient
    public String getPId() {
        if (parentMenu == null) {
            return "0";
        }
        return parentMenu.getId();
    }

    public Menu() {
    }

    public Menu(String id) {
        this.id = id;
    }

    public Menu(Menu parentMenu, String name, String description, String page, String generatemenu,
                Integer zindex, Set<Menu> children, Set<Role> roles) {
        this.parentMenu = parentMenu;
        this.name = name;
        this.description = description;
        this.page = page;
        this.generatemenu = generatemenu;
        this.zindex = zindex;
        this.children = children;
        this.roles = roles;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 32)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PID")
    public Menu getParentMenu() {
        return this.parentMenu;
    }

    public void setParentMenu(Menu parentMenu) {
        this.parentMenu = parentMenu;
    }

    @Column(name = "NAME", unique = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PAGE")
    public String getPage() {
        return this.page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    @Column(name = "GENERATEMENU")
    public String getGeneratemenu() {
        return this.generatemenu;
    }

    public void setGeneratemenu(String generatemenu) {
        this.generatemenu = generatemenu;
    }

    @Column(name = "ZINDEX", precision = 8, scale = 0)
    public Integer getZindex() {
        return this.zindex;
    }

    public void setZindex(Integer zindex) {
        this.zindex = zindex;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "parentMenu")
    @JSONField(serialize = false)
    public Set<Menu> getChildren() {
        return this.children;
    }

    public void setChildren(Set<Menu> children) {
        this.children = children;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "role_menu", catalog = "bos2", joinColumns = {
            @JoinColumn(name = "MENU_ID", nullable = false, updatable = false) },
            inverseJoinColumns = {
                    @JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) })
    @JSONField(serialize = false)
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

}


