package com.sirier.domain;
// Generated 2017-8-10 11:18:15 by Hibernate Tools 3.2.2.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Customer generated by hbm2java
 */
@XmlRootElement
public class Customer implements java.io.Serializable {

    private Integer id;
    private String name;
    private String telephone;
    private String address;
    private String station;
    private String decidedzoneId;

    public Customer() {
    }

    public Customer(String name, String telephone, String address) {
        this.name = name;
        this.telephone = telephone;
        this.address = address;
    }

    public Customer(String name, String telephone, String address, String station, String
            decidedzoneId) {
        this.name = name;
        this.telephone = telephone;
        this.address = address;
        this.station = station;
        this.decidedzoneId = decidedzoneId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getStation() {
        return this.station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    public String getDecidedzoneId() {
        return this.decidedzoneId;
    }

    public void setDecidedzoneId(String decidedzoneId) {
        this.decidedzoneId = decidedzoneId;
    }


    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", telephone='" + telephone + '\'' +
                ", address='" + address + '\'' +
                ", station='" + station + '\'' +
                ", decidedzoneId='" + decidedzoneId + '\'' +
                '}';
    }
}


